# Form implementation generated from reading ui file 'QtUI/RunnerQtUI/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file un`less you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import  time
import json
import logtool.log as log
import base64
import _thread

game_config_file = open("config.json","r")
game_config = json.loads(game_config_file.read())
game_config_file.close()

log.logINFO("Game config loaded.")

game_script_file = open("scripts/game.json","r")
game_script = json.loads(game_script_file.read())["game"]
game_script_file.close()

log.logINFO("Game script loaded.")

# 淡入淡出函数，采用setStyleSheet方法，对文字无效
def fade_in_out(qtobject, delay, fulldelay,pm):
    op = QtWidgets.QGraphicsOpacityEffect()
    op.setOpacity(0)
    qtobject.setGraphicsEffect(op)
    qtobject.setPixmap(pm)
    a = 0
    for i in range(100):
        log.logINFO("fade-in-out_+")
        a = a + 0.01
        time.sleep(float(delay))
        op.setOpacity(a)
    time.sleep(float(fulldelay))
    for i in range(100):
        log.logINFO("fade-in-out_-")
        a = a - 0.01
        time.sleep(float(delay))
        op.setOpacity(a)

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        log.logINFO("setupUi")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(game_config["game-window"]["x"], game_config["game-window"]["y"])
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, game_config["game-window"]["x"], 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setupStart(self):
        self.__image = QtWidgets.QLabel(self.centralwidget)
        self.__image.setGeometry(QtCore.QRect(0, 0, game_config["game-window"]["x"], game_config["game-window"]["y"]))
        self.__image.setObjectName("__image")
        _thread.start_new_thread(self.setupStart_,())

    def setupStart_(self):

        datafile_ = open(game_script["start"]["imagepath"], "r")
        data = json.loads(datafile_.read())
        datafile_.close()
        a = 0
        for i in game_script["start"]["imagelist"]:
            pm = QtGui.QPixmap()
            pm.loadFromData(base64.b64decode(data[i]["base64"]))
            fade_in_out(self.__image,game_script["start"]["delaylist"][a],game_script["start"]["fulldelaylist"][a],pm)
            a = a + 1

    def msg_critical(self, text):
        ConfigNotExistsErrorDialog = QtWidgets.QMessageBox()
        ConfigNotExistsErrorDialog.setWindowTitle("Error")
        ConfigNotExistsErrorDialog.setText(text)
        ConfigNotExistsErrorDialog.exec()